import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/providers/ThemeProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "@/components/ui/toaster";

const font = Roboto_Slab({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mehdi | Full stack developer",
  description: "Generated by Mehdi Znayzen",
  icons : "/assets/logos/logo.png"
};

const customAppearance = {
  baseTheme : dark,
  variables: {
      colorPrimary: '#30B2EF',
      colorBackground: '#E2EDF2',
      colorText: '#000',
      borderRadius: '8px',
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: customAppearance.baseTheme
      }}
    >
      <html 
        lang="en" 
        suppressHydrationWarning
      >
        <body className={font.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
